BEGIN;

-- The accountless quote broker is deliberately isolated from both the owner
-- executor and the public database roles. Only fixed SECURITY DEFINER
-- operations owned by this NOLOGIN role can use the broker grants below.
GRANT USAGE ON SCHEMA public, private, auth TO webameen_quote_broker;
GRANT EXECUTE ON FUNCTION auth.uid() TO webameen_quote_broker;

GRANT SELECT (business_id, disabled_at) ON public.business_memberships
  TO webameen_quote_broker;
GRANT SELECT (id, business_id, reference, current_version_id),
  UPDATE (updated_at) ON public.quotations TO webameen_quote_broker;
GRANT SELECT (
  id, business_id, quotation_id, version_number, previous_version_id, state,
  valid_until, response_deadline_at, shared_by, shared_at,
  seller_display_name, seller_contact_email, seller_contact_phone,
  seller_postal_address, seller_country_code, seller_state_code,
  seller_gst_registered, seller_gstin, seller_logo_asset_key, seller_logo_sha256,
  seller_signature_asset_key, seller_signature_sha256,
  buyer_display_name, buyer_contact_name, buyer_email, buyer_phone,
  buyer_billing_address, buyer_state_code, buyer_gstin_applicable, buyer_gstin,
  currency_code, currency_exponent, quantity_scale, calculation_rule_code,
  price_tax_mode, gst_auto_treatment, gst_treatment_override, gst_treatment,
  document_time_zone, place_of_supply_applicable, place_of_supply_state_code,
  place_of_supply_text, reverse_charge_applies,
  subtotal_minor, taxable_subtotal_minor, cgst_total_minor, sgst_total_minor,
  igst_total_minor, gst_total_minor, total_minor,
  seller_bank_name, seller_bank_account_name, seller_bank_account_number,
  seller_bank_ifsc, seller_upi_id, payment_instructions, terms
) ON public.quotation_versions TO webameen_quote_broker;
GRANT SELECT (
  business_id, version_id, position, description, unit_label, hsn_sac,
  quantity, unit_price_minor, line_subtotal_minor, gst_category, gst_treatment,
  gst_rate, taxable_amount_minor, cgst_rate, cgst_amount_minor, sgst_rate,
  sgst_amount_minor, igst_rate, igst_amount_minor, line_total_minor
) ON public.quotation_items TO webameen_quote_broker;
GRANT SELECT (
  id, business_id, quotation_id, version_id, token_hash,
  access_expires_at, created_at, revoked_at
) ON public.quotation_public_links TO webameen_quote_broker;
GRANT SELECT (
  id, business_id, quotation_id, version_id, public_link_id, kind,
  customer_note, respondent_name, responded_at
) ON public.quotation_responses TO webameen_quote_broker;
GRANT INSERT (
  business_id, quotation_id, version_id, public_link_id, kind,
  customer_note, respondent_name, responded_at
) ON public.quotation_responses TO webameen_quote_broker;
GRANT UPDATE (state) ON public.quotation_versions TO webameen_quote_broker;

-- The role is NOLOGIN and cannot be assumed by anon/authenticated/runtime
-- users. Token resolution and every relationship check live in the fixed
-- private broker functions below; these role-specific policies are never
-- granted to a public role.
CREATE POLICY quote_broker_membership_read ON public.business_memberships
  FOR SELECT TO webameen_quote_broker USING (true);
CREATE POLICY quote_broker_quotation_read ON public.quotations
  FOR SELECT TO webameen_quote_broker USING (true);
CREATE POLICY quote_broker_quotation_update ON public.quotations
  FOR UPDATE TO webameen_quote_broker USING (true) WITH CHECK (true);
CREATE POLICY quote_broker_version_read ON public.quotation_versions
  FOR SELECT TO webameen_quote_broker USING (shared_at IS NOT NULL);
CREATE POLICY quote_broker_version_update ON public.quotation_versions
  FOR UPDATE TO webameen_quote_broker
  USING (shared_at IS NOT NULL) WITH CHECK (shared_at IS NOT NULL);
CREATE POLICY quote_broker_item_read ON public.quotation_items
  FOR SELECT TO webameen_quote_broker USING (
    EXISTS (SELECT 1 FROM public.quotation_versions AS v
      WHERE v.business_id = quotation_items.business_id
        AND v.id = quotation_items.version_id AND v.shared_at IS NOT NULL)
  );
CREATE POLICY quote_broker_link_read ON public.quotation_public_links
  FOR SELECT TO webameen_quote_broker USING (true);
CREATE POLICY quote_broker_response_read ON public.quotation_responses
  FOR SELECT TO webameen_quote_broker USING (true);
CREATE POLICY quote_broker_response_insert ON public.quotation_responses
  FOR INSERT TO webameen_quote_broker WITH CHECK (true);

-- Share freezes the current complete draft and inserts its first bearer link
-- in one transaction. The token itself is generated by the server; only its
-- validated SHA-256 hex digest reaches this function.
CREATE FUNCTION private.share_quotation_draft(
  p_quotation_id uuid,
  p_version_id uuid,
  p_creation_request_key uuid,
  p_token_hash_hex text,
  p_access_expires_at timestamptz DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_user_id uuid := auth.uid();
  v_business_id uuid;
  v_quote public.quotations;
  v_version public.quotation_versions;
  v_existing public.quotation_public_links;
  v_now timestamptz;
  v_response_deadline timestamptz;
  v_line_count bigint;
BEGIN
  IF v_user_id IS NULL OR p_quotation_id IS NULL OR p_version_id IS NULL
    OR p_creation_request_key IS NULL OR p_token_hash_hex IS NULL
    OR p_token_hash_hex !~ '^[0-9a-fA-F]{64}$' THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Invalid quotation share request';
  END IF;
  -- Preserve the documented lock order: selectable GST options, business,
  -- then quotation. Recheck active membership after the business lock.
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/gst-options', 0));
  SELECT business_id INTO v_business_id FROM public.business_memberships
    WHERE user_id=v_user_id;
  IF v_business_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text, 0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships
    WHERE business_id=v_business_id AND user_id=v_user_id
      AND role='owner' AND disabled_at IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required';
  END IF;
  SELECT * INTO v_quote FROM public.quotations
    WHERE business_id=v_business_id AND id=p_quotation_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Quotation unavailable';
  END IF;

  -- Idempotency is resolved before checking whether this is still a draft.
  SELECT * INTO v_existing FROM public.quotation_public_links
    WHERE business_id=v_business_id AND creation_request_key=p_creation_request_key;
  IF FOUND THEN
    IF v_existing.quotation_id<>p_quotation_id
      OR v_existing.version_id<>p_version_id
      OR v_existing.access_expires_at IS DISTINCT FROM p_access_expires_at THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Share request key was used for different inputs';
    END IF;
    RETURN pg_catalog.jsonb_build_object(
      'link_id',v_existing.id,'created',false,
      'active',v_existing.revoked_at IS NULL AND
        (v_existing.access_expires_at IS NULL OR v_existing.access_expires_at>pg_catalog.clock_timestamp()),
      'access_expires_at',v_existing.access_expires_at);
  END IF;

  SELECT * INTO v_version FROM public.quotation_versions
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id AND id=p_version_id;
  IF NOT FOUND OR v_quote.current_version_id<>p_version_id
    OR v_version.state<>'draft' OR v_version.shared_at IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Only the current draft can be shared';
  END IF;
  IF EXISTS (SELECT 1 FROM public.invoices
      WHERE business_id=v_business_id AND quotation_id=p_quotation_id) THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='An invoiced quotation cannot be shared again';
  END IF;
  IF v_version.seller_display_name IS NULL OR pg_catalog.btrim(v_version.seller_display_name)=''
    OR v_version.seller_postal_address IS NULL OR pg_catalog.btrim(v_version.seller_postal_address)=''
    OR v_version.seller_country_code IS DISTINCT FROM 'IN'
    OR v_version.seller_state_code IS NULL
    OR v_version.seller_gst_registered IS NULL
    OR (v_version.seller_gst_registered AND
      (v_version.seller_gstin IS NULL OR v_version.seller_gstin !~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]{3}$'))
    OR v_version.buyer_display_name IS NULL OR pg_catalog.btrim(v_version.buyer_display_name)=''
    OR v_version.buyer_billing_address IS NULL OR pg_catalog.btrim(v_version.buyer_billing_address)=''
    OR v_version.buyer_state_code IS NULL
    OR v_version.buyer_gstin_applicable IS NULL
    OR (v_version.buyer_gstin_applicable AND
      (v_version.buyer_gstin IS NULL OR v_version.buyer_gstin !~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]{3}$'))
    OR v_version.currency_code IS DISTINCT FROM 'INR'
    OR v_version.currency_exponent IS DISTINCT FROM 2
    OR v_version.quantity_scale IS DISTINCT FROM 3
    OR v_version.calculation_rule_code IS DISTINCT FROM 'in-gst-exclusive-line-paise-half-up-v1'
    OR v_version.price_tax_mode IS DISTINCT FROM 'exclusive'
    OR v_version.document_time_zone IS NULL
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_timezone_names
        WHERE name=v_version.document_time_zone)
    OR v_version.place_of_supply_applicable IS NULL
    OR (v_version.place_of_supply_applicable AND v_version.place_of_supply_state_code IS NULL)
    OR (NOT v_version.place_of_supply_applicable AND
      (v_version.place_of_supply_state_code IS NOT NULL OR v_version.place_of_supply_text IS NOT NULL))
    OR v_version.reverse_charge_applies IS NULL
    OR v_version.gst_auto_treatment IS DISTINCT FROM
      (CASE WHEN v_version.seller_state_code=v_version.buyer_state_code THEN 'cgst_sgst' ELSE 'igst' END)
    OR v_version.gst_treatment IS DISTINCT FROM
      COALESCE(v_version.gst_treatment_override,v_version.gst_auto_treatment) THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Complete and review the quotation details before sharing';
  END IF;
  IF v_version.seller_contact_email IS NOT NULL AND
       v_version.seller_contact_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    OR v_version.buyer_email IS NOT NULL AND
       v_version.buyer_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Correct the email address before sharing';
  END IF;
  SELECT count(*) INTO v_line_count FROM public.quotation_items
    WHERE business_id=v_business_id AND version_id=p_version_id;
  IF v_line_count=0 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Add at least one quotation line before sharing';
  END IF;
  IF EXISTS (SELECT 1 FROM public.quotation_items AS i
      WHERE i.business_id=v_business_id AND i.version_id=p_version_id
        AND i.gst_category='taxable'
        AND NOT EXISTS (SELECT 1 FROM public.gst_rate_options AS r
          WHERE r.rate=i.gst_rate AND r.selectable)) THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Select a currently configured GST rate before sharing';
  END IF;
  IF (v_version.seller_logo_asset_key IS NULL)<>(v_version.seller_logo_sha256 IS NULL)
    OR (v_version.seller_signature_asset_key IS NULL)<>(v_version.seller_signature_sha256 IS NULL)
    OR (v_version.seller_logo_sha256 IS NOT NULL AND pg_catalog.octet_length(v_version.seller_logo_sha256)<>32)
    OR (v_version.seller_signature_sha256 IS NOT NULL AND pg_catalog.octet_length(v_version.seller_signature_sha256)<>32) THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='A configured document image is unavailable';
  END IF;
  v_now := pg_catalog.clock_timestamp();
  IF v_version.valid_until IS NOT NULL THEN
    v_response_deadline := (v_version.valid_until + 1)::timestamp AT TIME ZONE v_version.document_time_zone;
    IF v_response_deadline<=v_now THEN
      RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='The quotation response deadline has passed';
    END IF;
  END IF;
  IF p_access_expires_at IS NOT NULL AND p_access_expires_at<=v_now THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='The link access cutoff must be in the future';
  END IF;

  UPDATE public.quotation_public_links SET
    revoked_by=v_user_id,revoked_at=v_now,revocation_reason='revision_shared'
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id AND revoked_at IS NULL;
  UPDATE public.quotation_versions SET
    state='shared',shared_by=v_user_id,shared_at=v_now,
    response_deadline_at=v_response_deadline
    WHERE business_id=v_business_id AND id=p_version_id;
  INSERT INTO public.quotation_public_links(
    business_id,quotation_id,version_id,token_hash,creation_request_key,
    access_expires_at,created_by,created_at)
  VALUES (v_business_id,p_quotation_id,p_version_id,
    pg_catalog.decode(p_token_hash_hex,'hex'),p_creation_request_key,
    p_access_expires_at,v_user_id,v_now)
  RETURNING * INTO v_existing;
  UPDATE public.quotations SET updated_at=v_now
    WHERE business_id=v_business_id AND id=p_quotation_id;
  RETURN pg_catalog.jsonb_build_object(
    'link_id',v_existing.id,'created',true,'active',true,
    'access_expires_at',v_existing.access_expires_at);
END
$fn$;

CREATE FUNCTION private.rotate_quotation_link(
  p_quotation_id uuid,
  p_version_id uuid,
  p_creation_request_key uuid,
  p_token_hash_hex text,
  p_access_expires_at timestamptz DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_user_id uuid := auth.uid();
  v_business_id uuid;
  v_quote public.quotations;
  v_version public.quotation_versions;
  v_existing public.quotation_public_links;
  v_now timestamptz;
BEGIN
  IF v_user_id IS NULL OR p_quotation_id IS NULL OR p_version_id IS NULL OR p_creation_request_key IS NULL
    OR p_token_hash_hex IS NULL OR p_token_hash_hex !~ '^[0-9a-fA-F]{64}$' THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Invalid quotation link request';
  END IF;
  SELECT business_id INTO v_business_id FROM public.business_memberships WHERE user_id=v_user_id;
  IF v_business_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text,0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships
    WHERE business_id=v_business_id AND user_id=v_user_id AND role='owner' AND disabled_at IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required';
  END IF;
  SELECT * INTO v_quote FROM public.quotations
    WHERE business_id=v_business_id AND id=p_quotation_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Quotation unavailable'; END IF;
  SELECT * INTO v_existing FROM public.quotation_public_links
    WHERE business_id=v_business_id AND creation_request_key=p_creation_request_key;
  IF FOUND THEN
    IF v_existing.quotation_id<>p_quotation_id
      OR v_existing.version_id<>p_version_id
      OR v_existing.access_expires_at IS DISTINCT FROM p_access_expires_at THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Link request key was used for different inputs';
    END IF;
    RETURN pg_catalog.jsonb_build_object(
      'link_id',v_existing.id,'created',false,
      'active',v_existing.revoked_at IS NULL AND
        (v_existing.access_expires_at IS NULL OR v_existing.access_expires_at>pg_catalog.clock_timestamp()),
      'access_expires_at',v_existing.access_expires_at);
  END IF;
  SELECT * INTO v_version FROM public.quotation_versions
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id
      AND id=p_version_id;
  IF NOT FOUND OR v_quote.current_version_id<>p_version_id
    OR v_version.shared_at IS NULL OR v_version.state='superseded'
    OR EXISTS (SELECT 1 FROM public.invoices
      WHERE business_id=v_business_id AND quotation_id=p_quotation_id) THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Only the current frozen quotation can have its link rotated';
  END IF;
  v_now:=pg_catalog.clock_timestamp();
  IF p_access_expires_at IS NOT NULL AND p_access_expires_at<=v_now THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='The link access cutoff must be in the future';
  END IF;
  UPDATE public.quotation_public_links SET
    revoked_by=v_user_id,revoked_at=v_now,revocation_reason='rotated'
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id AND revoked_at IS NULL;
  INSERT INTO public.quotation_public_links(
    business_id,quotation_id,version_id,token_hash,creation_request_key,
    access_expires_at,created_by,created_at)
  VALUES (v_business_id,p_quotation_id,v_version.id,
    pg_catalog.decode(p_token_hash_hex,'hex'),p_creation_request_key,
    p_access_expires_at,v_user_id,v_now)
  RETURNING * INTO v_existing;
  UPDATE public.quotations SET updated_at=v_now
    WHERE business_id=v_business_id AND id=p_quotation_id;
  RETURN pg_catalog.jsonb_build_object(
    'link_id',v_existing.id,'created',true,'active',true,
    'access_expires_at',v_existing.access_expires_at);
END
$fn$;

CREATE FUNCTION private.revoke_quotation_link(
  p_quotation_id uuid,p_link_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_user_id uuid := auth.uid(); v_business_id uuid;
  v_quote public.quotations; v_link public.quotation_public_links;
  v_now timestamptz;
BEGIN
  IF v_user_id IS NULL OR p_quotation_id IS NULL OR p_link_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Authenticated owner required';
  END IF;
  SELECT business_id INTO v_business_id FROM public.business_memberships WHERE user_id=v_user_id;
  IF v_business_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text,0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships
    WHERE business_id=v_business_id AND user_id=v_user_id AND role='owner' AND disabled_at IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required';
  END IF;
  SELECT * INTO v_quote FROM public.quotations
    WHERE business_id=v_business_id AND id=p_quotation_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Quotation unavailable'; END IF;
  SELECT * INTO v_link FROM public.quotation_public_links
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id AND id=p_link_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Quotation link unavailable'; END IF;
  IF v_link.revoked_at IS NULL THEN
    v_now:=pg_catalog.clock_timestamp();
    UPDATE public.quotation_public_links SET
      revoked_by=v_user_id,revoked_at=v_now,revocation_reason='owner_revoked'
      WHERE business_id=v_business_id AND id=p_link_id;
    UPDATE public.quotations SET updated_at=v_now
      WHERE business_id=v_business_id AND id=p_quotation_id;
    v_link.revoked_at:=v_now;
    v_link.revoked_by:=v_user_id;
    v_link.revocation_reason:='owner_revoked';
  END IF;
  RETURN pg_catalog.jsonb_build_object(
    'link_id',v_link.id,'revoked_at',v_link.revoked_at,
    'revocation_reason',v_link.revocation_reason);
END
$fn$;

CREATE FUNCTION private.create_quotation_revision(
  p_quotation_id uuid,p_predecessor_version_id uuid
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_user_id uuid:=auth.uid(); v_business_id uuid;
  v_quote public.quotations; v_predecessor public.quotation_versions;
  v_successor public.quotation_versions; v_new_id uuid:=pg_catalog.gen_random_uuid();
  v_now timestamptz;
BEGIN
  IF v_user_id IS NULL OR p_quotation_id IS NULL OR p_predecessor_version_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Authenticated owner required';
  END IF;
  SELECT business_id INTO v_business_id FROM public.business_memberships WHERE user_id=v_user_id;
  IF v_business_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text,0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships
    WHERE business_id=v_business_id AND user_id=v_user_id AND role='owner' AND disabled_at IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Active owner required';
  END IF;
  SELECT * INTO v_quote FROM public.quotations
    WHERE business_id=v_business_id AND id=p_quotation_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Quotation unavailable'; END IF;

  -- A retry of a revision returns its original successor, even if later
  -- workflow steps have already advanced the quotation.
  SELECT * INTO v_successor FROM public.quotation_versions
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id
      AND previous_version_id=p_predecessor_version_id;
  IF FOUND THEN RETURN v_successor.id; END IF;
  IF EXISTS (SELECT 1 FROM public.invoices
      WHERE business_id=v_business_id AND quotation_id=p_quotation_id) THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='An invoiced quotation cannot be revised';
  END IF;
  IF v_quote.current_version_id<>p_predecessor_version_id THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Only the current quotation version can be revised';
  END IF;
  SELECT * INTO v_predecessor FROM public.quotation_versions
    WHERE business_id=v_business_id AND quotation_id=p_quotation_id
      AND id=p_predecessor_version_id FOR UPDATE;
  IF NOT FOUND OR v_predecessor.shared_at IS NULL OR v_predecessor.state='superseded' THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Only a frozen quotation can be revised';
  END IF;
  v_now:=pg_catalog.clock_timestamp();
  INSERT INTO public.quotation_versions(
    id,business_id,quotation_id,version_number,previous_version_id,state,edit_sequence,
    created_by,created_at,edited_at,valid_until,
    seller_display_name,seller_contact_email,seller_contact_phone,seller_postal_address,
    seller_country_code,seller_state_code,seller_gst_registered,seller_gstin,
    seller_logo_asset_key,seller_logo_sha256,seller_signature_asset_key,seller_signature_sha256,
    buyer_display_name,buyer_contact_name,buyer_email,buyer_phone,buyer_billing_address,
    buyer_state_code,buyer_gstin_applicable,buyer_gstin,
    currency_code,currency_exponent,quantity_scale,calculation_rule_code,price_tax_mode,
    gst_auto_treatment,gst_treatment_override,gst_treatment,document_time_zone,
    place_of_supply_applicable,place_of_supply_state_code,place_of_supply_text,reverse_charge_applies,
    subtotal_minor,taxable_subtotal_minor,cgst_total_minor,sgst_total_minor,igst_total_minor,
    gst_total_minor,total_minor,seller_bank_name,seller_bank_account_name,
    seller_bank_account_number,seller_bank_ifsc,seller_upi_id,payment_instructions,terms
  ) VALUES (
    v_new_id,v_business_id,p_quotation_id,v_predecessor.version_number+1,
    v_predecessor.id,'draft',0,v_user_id,v_now,v_now,v_predecessor.valid_until,
    v_predecessor.seller_display_name,v_predecessor.seller_contact_email,
    v_predecessor.seller_contact_phone,v_predecessor.seller_postal_address,
    v_predecessor.seller_country_code,v_predecessor.seller_state_code,
    v_predecessor.seller_gst_registered,v_predecessor.seller_gstin,
    v_predecessor.seller_logo_asset_key,v_predecessor.seller_logo_sha256,
    v_predecessor.seller_signature_asset_key,v_predecessor.seller_signature_sha256,
    v_predecessor.buyer_display_name,v_predecessor.buyer_contact_name,
    v_predecessor.buyer_email,v_predecessor.buyer_phone,v_predecessor.buyer_billing_address,
    v_predecessor.buyer_state_code,v_predecessor.buyer_gstin_applicable,v_predecessor.buyer_gstin,
    v_predecessor.currency_code,v_predecessor.currency_exponent,v_predecessor.quantity_scale,
    v_predecessor.calculation_rule_code,v_predecessor.price_tax_mode,
    v_predecessor.gst_auto_treatment,v_predecessor.gst_treatment_override,v_predecessor.gst_treatment,
    v_predecessor.document_time_zone,v_predecessor.place_of_supply_applicable,
    v_predecessor.place_of_supply_state_code,v_predecessor.place_of_supply_text,
    v_predecessor.reverse_charge_applies,
    v_predecessor.subtotal_minor,v_predecessor.taxable_subtotal_minor,v_predecessor.cgst_total_minor,
    v_predecessor.sgst_total_minor,v_predecessor.igst_total_minor,v_predecessor.gst_total_minor,
    v_predecessor.total_minor,v_predecessor.seller_bank_name,v_predecessor.seller_bank_account_name,
    v_predecessor.seller_bank_account_number,v_predecessor.seller_bank_ifsc,
    v_predecessor.seller_upi_id,v_predecessor.payment_instructions,v_predecessor.terms
  );
  INSERT INTO public.quotation_items(
    business_id,version_id,source_catalog_item_id,position,description,unit_label,hsn_sac,
    quantity,unit_price_minor,line_subtotal_minor,gst_category,gst_treatment,gst_rate,
    taxable_amount_minor,cgst_rate,cgst_amount_minor,sgst_rate,sgst_amount_minor,
    igst_rate,igst_amount_minor,line_total_minor
  ) SELECT business_id,v_new_id,source_catalog_item_id,position,description,unit_label,hsn_sac,
    quantity,unit_price_minor,line_subtotal_minor,gst_category,gst_treatment,gst_rate,
    taxable_amount_minor,cgst_rate,cgst_amount_minor,sgst_rate,sgst_amount_minor,
    igst_rate,igst_amount_minor,line_total_minor
    FROM public.quotation_items
    WHERE business_id=v_business_id AND version_id=p_predecessor_version_id
    ORDER BY position;
  UPDATE public.quotation_versions SET
    state='superseded',superseded_by=v_user_id,superseded_at=v_now
    WHERE business_id=v_business_id AND id=v_predecessor.id;
  UPDATE public.quotations SET current_version_id=v_new_id,updated_at=v_now
    WHERE business_id=v_business_id AND id=p_quotation_id;
  RETURN v_new_id;
END
$fn$;

-- Owner-only workflow history projection. It never returns bearer-token hashes
-- or request keys and includes only link status and customer response evidence.
CREATE FUNCTION public.get_quotation_workflow(p_quotation_id uuid)
RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$
  SELECT pg_catalog.jsonb_build_object(
    'quotation_id',q.id,'reference',q.reference,'current_version_id',q.current_version_id,
    'versions',COALESCE((SELECT pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id',v.id,'version_number',v.version_number,'state',v.state,
        'created_at',v.created_at,'shared_at',v.shared_at,
        'valid_until',v.valid_until,'response_deadline_at',v.response_deadline_at,
        'total_minor',v.total_minor::text,
        'response',(SELECT pg_catalog.jsonb_build_object(
          'kind',r.kind,'customer_note',r.customer_note,
          'respondent_name',r.respondent_name,'responded_at',r.responded_at)
          FROM public.quotation_responses AS r
          WHERE r.business_id=v.business_id AND r.version_id=v.id),
        'links',COALESCE((SELECT pg_catalog.jsonb_agg(
          pg_catalog.jsonb_build_object(
            'id',l.id,'created_at',l.created_at,
            'access_expires_at',l.access_expires_at,'revoked_at',l.revoked_at,
            'revocation_reason',l.revocation_reason,
            'active',l.revoked_at IS NULL AND
              (l.access_expires_at IS NULL OR l.access_expires_at>pg_catalog.clock_timestamp()))
          ORDER BY l.created_at DESC)
          FROM public.quotation_public_links AS l
          WHERE l.business_id=v.business_id AND l.quotation_id=v.quotation_id AND l.version_id=v.id),'[]'::jsonb)
      ) ORDER BY v.version_number DESC)
      FROM public.quotation_versions AS v
      WHERE v.business_id=q.business_id AND v.quotation_id=q.id),'[]'::jsonb)
  )
  FROM public.quotations AS q WHERE q.id=p_quotation_id
$fn$;

CREATE FUNCTION public.share_quotation_draft(
  p_quotation_id uuid,p_version_id uuid,p_creation_request_key uuid,
  p_token_hash_hex text,p_access_expires_at timestamptz DEFAULT NULL
) RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.share_quotation_draft(
  p_quotation_id,p_version_id,p_creation_request_key,p_token_hash_hex,p_access_expires_at) $fn$;
CREATE FUNCTION public.rotate_quotation_link(
  p_quotation_id uuid,p_version_id uuid,p_creation_request_key uuid,p_token_hash_hex text,
  p_access_expires_at timestamptz DEFAULT NULL
) RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.rotate_quotation_link(
  p_quotation_id,p_version_id,p_creation_request_key,p_token_hash_hex,p_access_expires_at) $fn$;
CREATE FUNCTION public.revoke_quotation_link(p_quotation_id uuid,p_link_id uuid)
RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.revoke_quotation_link(p_quotation_id,p_link_id) $fn$;
CREATE FUNCTION public.create_quotation_revision(p_quotation_id uuid,p_predecessor_version_id uuid)
RETURNS uuid LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.create_quotation_revision(p_quotation_id,p_predecessor_version_id) $fn$;

-- Fixed broker reads return a public DTO, never raw tenant rows. The caller
-- supplies only a SHA-256 digest; quote/version IDs are resolved from it.
CREATE FUNCTION private.read_public_quotation(p_token_hash_hex text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=''
AS $fn$
DECLARE
  v_hash bytea; v_business_id uuid; v_quote_id uuid; v_version_id uuid;
  v_link record; v_quote record; v_version record; v_response record;
  v_now timestamptz;
BEGIN
  IF p_token_hash_hex IS NULL OR p_token_hash_hex !~ '^[0-9a-fA-F]{64}$' THEN RETURN NULL; END IF;
  v_hash:=pg_catalog.decode(p_token_hash_hex,'hex');
  SELECT l.business_id,l.quotation_id,l.version_id
    INTO v_business_id,v_quote_id,v_version_id
    FROM public.quotation_public_links AS l WHERE l.token_hash=v_hash;
  IF NOT FOUND THEN RETURN NULL; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text,0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships AS m
    WHERE m.business_id=v_business_id AND m.disabled_at IS NULL) THEN RETURN NULL; END IF;
  SELECT q.id,q.business_id,q.reference,q.current_version_id INTO v_quote FROM public.quotations AS q
    WHERE q.business_id=v_business_id AND q.id=v_quote_id FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  SELECT l.id,l.business_id,l.quotation_id,l.version_id,l.token_hash,
      l.access_expires_at,l.created_at,l.revoked_at INTO v_link
    FROM public.quotation_public_links AS l
    WHERE l.business_id=v_business_id AND l.quotation_id=v_quote_id
      AND l.version_id=v_version_id AND l.token_hash=v_hash;
  IF NOT FOUND OR v_link.revoked_at IS NOT NULL THEN RETURN NULL; END IF;
  v_now:=pg_catalog.clock_timestamp();
  IF v_link.access_expires_at IS NOT NULL AND v_now>=v_link.access_expires_at THEN RETURN NULL; END IF;
  SELECT v.id,v.business_id,v.quotation_id,v.version_number,v.previous_version_id,v.state,
      v.valid_until,v.response_deadline_at,v.shared_by,v.shared_at,
      v.seller_display_name,v.seller_contact_email,v.seller_contact_phone,
      v.seller_postal_address,v.seller_country_code,v.seller_state_code,
      v.seller_gst_registered,v.seller_gstin,v.buyer_display_name,v.buyer_contact_name,
      v.buyer_email,v.buyer_phone,v.buyer_billing_address,v.buyer_state_code,
      v.buyer_gstin_applicable,v.buyer_gstin,v.currency_code,v.currency_exponent,
      v.quantity_scale,v.calculation_rule_code,v.price_tax_mode,v.gst_auto_treatment,
      v.gst_treatment_override,v.gst_treatment,v.document_time_zone,
      v.place_of_supply_applicable,v.place_of_supply_state_code,v.place_of_supply_text,
      v.reverse_charge_applies,v.subtotal_minor,v.taxable_subtotal_minor,
      v.cgst_total_minor,v.sgst_total_minor,v.igst_total_minor,v.gst_total_minor,
      v.total_minor,v.seller_bank_name,v.seller_bank_account_name,
      v.seller_bank_account_number,v.seller_bank_ifsc,v.seller_upi_id,
      v.payment_instructions,v.terms INTO v_version
    FROM public.quotation_versions AS v
    WHERE v.business_id=v_business_id AND v.quotation_id=v_quote_id
      AND v.id=v_version_id AND v.shared_at IS NOT NULL;
  IF NOT FOUND THEN RETURN NULL; END IF;
  SELECT r.id,r.public_link_id,r.kind,r.customer_note,r.respondent_name,r.responded_at
    INTO v_response FROM public.quotation_responses AS r
    WHERE r.business_id=v_business_id AND r.quotation_id=v_quote_id AND r.version_id=v_version_id;
  RETURN pg_catalog.jsonb_build_object(
    'reference',v_quote.reference,'version_number',v_version.version_number,
    'state',v_version.state,'revision_in_preparation',v_quote.current_version_id<>v_version.id,
    'valid_until',v_version.valid_until,'response_deadline_at',v_version.response_deadline_at,
    'response_deadline_passed',v_version.response_deadline_at IS NOT NULL AND v_now>=v_version.response_deadline_at,
    'seller',pg_catalog.jsonb_build_object(
      'display_name',v_version.seller_display_name,'email',v_version.seller_contact_email,
      'phone',v_version.seller_contact_phone,'address',v_version.seller_postal_address,
      'country_code',v_version.seller_country_code,'state_code',v_version.seller_state_code,
      'gst_registered',v_version.seller_gst_registered,'gstin',v_version.seller_gstin,
      'bank_name',v_version.seller_bank_name,'bank_account_name',v_version.seller_bank_account_name,
      'bank_account_number',v_version.seller_bank_account_number,'bank_ifsc',v_version.seller_bank_ifsc,
      'upi_id',v_version.seller_upi_id,'payment_instructions',v_version.payment_instructions),
    'buyer',pg_catalog.jsonb_build_object(
      'display_name',v_version.buyer_display_name,'contact_name',v_version.buyer_contact_name,
      'email',v_version.buyer_email,'phone',v_version.buyer_phone,
      'billing_address',v_version.buyer_billing_address,'state_code',v_version.buyer_state_code,
      'gstin_applicable',v_version.buyer_gstin_applicable,'gstin',v_version.buyer_gstin),
    'document',pg_catalog.jsonb_build_object(
      'currency_code',v_version.currency_code,'currency_exponent',v_version.currency_exponent,
      'quantity_scale',v_version.quantity_scale,'calculation_rule_code',v_version.calculation_rule_code,
      'price_tax_mode',v_version.price_tax_mode,'gst_auto_treatment',v_version.gst_auto_treatment,
      'gst_treatment_override',v_version.gst_treatment_override,'gst_treatment',v_version.gst_treatment,
      'document_time_zone',v_version.document_time_zone,
      'place_of_supply_applicable',v_version.place_of_supply_applicable,
      'place_of_supply_state_code',v_version.place_of_supply_state_code,
      'place_of_supply_text',v_version.place_of_supply_text,
      'reverse_charge_applies',v_version.reverse_charge_applies,'terms',v_version.terms),
    'totals',pg_catalog.jsonb_build_object(
      'subtotal_minor',v_version.subtotal_minor::text,
      'taxable_subtotal_minor',v_version.taxable_subtotal_minor::text,
      'cgst_total_minor',v_version.cgst_total_minor::text,
      'sgst_total_minor',v_version.sgst_total_minor::text,
      'igst_total_minor',v_version.igst_total_minor::text,
      'gst_total_minor',v_version.gst_total_minor::text,'total_minor',v_version.total_minor::text),
    'lines',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
      'position',i.position,'description',i.description,'unit_label',i.unit_label,
      'hsn_sac',i.hsn_sac,'quantity',i.quantity::text,
      'unit_price_minor',i.unit_price_minor::text,
      'line_subtotal_minor',i.line_subtotal_minor::text,
      'gst_category',i.gst_category,'gst_treatment',i.gst_treatment,
      'gst_rate',i.gst_rate::text,'taxable_amount_minor',i.taxable_amount_minor::text,
      'cgst_rate',i.cgst_rate::text,'cgst_amount_minor',i.cgst_amount_minor::text,
      'sgst_rate',i.sgst_rate::text,'sgst_amount_minor',i.sgst_amount_minor::text,
      'igst_rate',i.igst_rate::text,'igst_amount_minor',i.igst_amount_minor::text,
      'line_total_minor',i.line_total_minor::text)
      ORDER BY i.position) FROM public.quotation_items AS i
      WHERE i.business_id=v_business_id AND i.version_id=v_version_id),'[]'::jsonb),
    'response',CASE WHEN v_response.id IS NULL THEN NULL ELSE pg_catalog.jsonb_build_object(
      'kind',v_response.kind,'customer_note',v_response.customer_note,
      'respondent_name',v_response.respondent_name,'responded_at',v_response.responded_at) END
  );
END
$fn$;

CREATE FUNCTION private.respond_to_public_quotation(
  p_token_hash_hex text,p_kind text,p_customer_note text,p_respondent_name text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=''
AS $fn$
DECLARE
  v_hash bytea; v_business_id uuid; v_quote_id uuid; v_version_id uuid;
  v_link record; v_quote record; v_version record; v_existing record;
  v_now timestamptz; v_note text:=NULLIF(pg_catalog.btrim(p_customer_note),'');
  v_name text:=NULLIF(pg_catalog.btrim(p_respondent_name),'');
BEGIN
  IF p_token_hash_hex IS NULL OR p_token_hash_hex !~ '^[0-9a-fA-F]{64}$'
    OR p_kind IS NULL OR p_kind NOT IN ('approved','change_requested')
    OR pg_catalog.length(COALESCE(v_note,''))>2000
    OR pg_catalog.length(COALESCE(v_name,''))>200 THEN
    RETURN pg_catalog.jsonb_build_object('status','invalid');
  END IF;
  v_hash:=pg_catalog.decode(p_token_hash_hex,'hex');
  SELECT l.business_id,l.quotation_id,l.version_id
    INTO v_business_id,v_quote_id,v_version_id
    FROM public.quotation_public_links AS l WHERE l.token_hash=v_hash;
  IF NOT FOUND THEN RETURN pg_catalog.jsonb_build_object('status','unavailable'); END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock_shared(
    pg_catalog.hashtextextended('webameen/business/'||v_business_id::text,0));
  IF NOT EXISTS (SELECT 1 FROM public.business_memberships AS m
    WHERE m.business_id=v_business_id AND m.disabled_at IS NULL) THEN
    RETURN pg_catalog.jsonb_build_object('status','unavailable');
  END IF;
  SELECT q.id,q.business_id,q.reference,q.current_version_id INTO v_quote FROM public.quotations AS q
    WHERE q.business_id=v_business_id AND q.id=v_quote_id FOR UPDATE;
  IF NOT FOUND THEN RETURN pg_catalog.jsonb_build_object('status','unavailable'); END IF;
  SELECT l.id,l.business_id,l.quotation_id,l.version_id,l.token_hash,
      l.access_expires_at,l.created_at,l.revoked_at INTO v_link
    FROM public.quotation_public_links AS l
    WHERE l.business_id=v_business_id AND l.quotation_id=v_quote_id
      AND l.version_id=v_version_id AND l.token_hash=v_hash;
  IF NOT FOUND OR v_link.revoked_at IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('status','unavailable');
  END IF;
  v_now:=pg_catalog.clock_timestamp();
  IF v_link.access_expires_at IS NOT NULL AND v_now>=v_link.access_expires_at THEN
    RETURN pg_catalog.jsonb_build_object('status','unavailable');
  END IF;
  IF v_quote.current_version_id<>v_version_id THEN
    RETURN pg_catalog.jsonb_build_object('status','unavailable');
  END IF;
  SELECT v.id,v.business_id,v.quotation_id,v.state,v.shared_at,v.response_deadline_at
    INTO v_version FROM public.quotation_versions AS v
    WHERE v.business_id=v_business_id AND v.quotation_id=v_quote_id
      AND v.id=v_version_id AND v.shared_at IS NOT NULL;
  IF NOT FOUND THEN RETURN pg_catalog.jsonb_build_object('status','unavailable'); END IF;
  SELECT r.id,r.business_id,r.quotation_id,r.version_id,r.public_link_id,r.kind,
      r.customer_note,r.respondent_name,r.responded_at INTO v_existing
    FROM public.quotation_responses AS r
    WHERE r.business_id=v_business_id AND r.version_id=v_version_id;
  IF FOUND THEN
    IF v_existing.public_link_id=v_link.id AND v_existing.kind=p_kind
      AND v_existing.customer_note IS NOT DISTINCT FROM v_note
      AND v_existing.respondent_name IS NOT DISTINCT FROM v_name THEN
      RETURN pg_catalog.jsonb_build_object('status','recorded','kind',v_existing.kind,
        'responded_at',v_existing.responded_at);
    END IF;
    RETURN pg_catalog.jsonb_build_object('status','already_responded',
      'kind',v_existing.kind,'responded_at',v_existing.responded_at);
  END IF;
  IF v_version.state<>'shared' THEN
    RETURN pg_catalog.jsonb_build_object('status','already_responded');
  END IF;
  IF v_version.response_deadline_at IS NOT NULL AND v_now>=v_version.response_deadline_at THEN
    RETURN pg_catalog.jsonb_build_object('status','expired');
  END IF;
  INSERT INTO public.quotation_responses(
    business_id,quotation_id,version_id,public_link_id,kind,
    customer_note,respondent_name,responded_at)
  VALUES(v_business_id,v_quote_id,v_version_id,v_link.id,p_kind,v_note,v_name,v_now);
  UPDATE public.quotation_versions SET state=p_kind
    WHERE business_id=v_business_id AND id=v_version_id;
  UPDATE public.quotations SET updated_at=v_now
    WHERE business_id=v_business_id AND id=v_quote_id;
  RETURN pg_catalog.jsonb_build_object('status','recorded','kind',p_kind,'responded_at',v_now);
END
$fn$;

CREATE FUNCTION public.read_public_quotation(p_token_hash_hex text)
RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.read_public_quotation(p_token_hash_hex) $fn$;
CREATE FUNCTION public.respond_to_public_quotation(
  p_token_hash_hex text,p_kind text,p_customer_note text DEFAULT NULL,
  p_respondent_name text DEFAULT NULL
) RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path=''
AS $fn$ SELECT private.respond_to_public_quotation(
  p_token_hash_hex,p_kind,p_customer_note,p_respondent_name) $fn$;

-- Public Data API callers have no access to these operations. The isolated
-- server broker key invokes only these fixed wrappers/private functions.
REVOKE ALL ON FUNCTION private.share_quotation_draft(uuid,uuid,uuid,text,timestamptz)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION private.rotate_quotation_link(uuid,uuid,uuid,text,timestamptz)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION private.revoke_quotation_link(uuid,uuid)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION private.create_quotation_revision(uuid,uuid)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION private.read_public_quotation(text)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION private.respond_to_public_quotation(text,text,text,text)
  FROM PUBLIC,anon,authenticated,service_role,webameen_quote_broker;
REVOKE ALL ON FUNCTION public.get_quotation_workflow(uuid)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.share_quotation_draft(uuid,uuid,uuid,text,timestamptz)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.rotate_quotation_link(uuid,uuid,uuid,text,timestamptz)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.revoke_quotation_link(uuid,uuid)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.create_quotation_revision(uuid,uuid)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.read_public_quotation(text)
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.respond_to_public_quotation(text,text,text,text)
  FROM PUBLIC,anon,authenticated,service_role;

GRANT EXECUTE ON FUNCTION private.share_quotation_draft(uuid,uuid,uuid,text,timestamptz),
  private.rotate_quotation_link(uuid,uuid,uuid,text,timestamptz),
  private.revoke_quotation_link(uuid,uuid),
  private.create_quotation_revision(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.read_public_quotation(text),
  private.respond_to_public_quotation(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_quotation_workflow(uuid),
  public.share_quotation_draft(uuid,uuid,uuid,text,timestamptz),
  public.rotate_quotation_link(uuid,uuid,uuid,text,timestamptz),
  public.revoke_quotation_link(uuid,uuid),
  public.create_quotation_revision(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.read_public_quotation(text),
  public.respond_to_public_quotation(text,text,text,text) TO service_role;
GRANT USAGE ON SCHEMA private TO service_role;

GRANT webameen_executor,webameen_quote_broker TO CURRENT_USER WITH INHERIT FALSE, SET TRUE;
-- PostgreSQL requires each target owner to hold CREATE on the containing
-- schema during ownership transfer. Remove both temporary privileges below.
GRANT CREATE ON SCHEMA private TO webameen_executor,webameen_quote_broker;

ALTER FUNCTION private.share_quotation_draft(uuid,uuid,uuid,text,timestamptz)
  OWNER TO webameen_executor;
ALTER FUNCTION private.rotate_quotation_link(uuid,uuid,uuid,text,timestamptz)
  OWNER TO webameen_executor;
ALTER FUNCTION private.revoke_quotation_link(uuid,uuid)
  OWNER TO webameen_executor;
ALTER FUNCTION private.create_quotation_revision(uuid,uuid)
  OWNER TO webameen_executor;
ALTER FUNCTION private.read_public_quotation(text)
  OWNER TO webameen_quote_broker;
ALTER FUNCTION private.respond_to_public_quotation(text,text,text,text)
  OWNER TO webameen_quote_broker;
REVOKE CREATE ON SCHEMA private FROM webameen_executor,webameen_quote_broker;

REVOKE webameen_executor,webameen_quote_broker FROM CURRENT_USER;

ALTER TABLE public.business_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_memberships FORCE ROW LEVEL SECURITY;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotations FORCE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_items FORCE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_public_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_public_links FORCE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_responses FORCE ROW LEVEL SECURITY;

COMMIT;
